# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [12]:
import numpy as np
a = np.arange(1,12,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
[i*-1 if i>=3 and i<=6 else i*1 for i in a ]

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]

In [31]:
a[(a>=3)&(a<=6)]*=-1
a

array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10, 11])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [32]:
A = np.random.rand(3, 6)
A

array([[0.20145621, 0.9407791 , 0.40359746, 0.53888058, 0.87318243,
        0.82539853],
       [0.95899318, 0.29870862, 0.30794874, 0.30109872, 0.99704421,
        0.87305656],
       [0.650821  , 0.86739316, 0.65041693, 0.68635314, 0.29191263,
        0.66314013]])

In [46]:
print(A>0.5)
print(A[A>0.5])

[[False  True False  True  True  True]
 [ True False False False  True  True]
 [ True  True  True  True False  True]]
[0.9407791  0.53888058 0.87318243 0.82539853 0.95899318 0.99704421
 0.87305656 0.650821   0.86739316 0.65041693 0.68635314 0.66314013]


In [40]:
len(A[A>0.5])

12

In [45]:
A[A>0.5].size

12