# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
a = np.random.rand(2, 3)
np.round(a)

array([[0., 1., 0.],
       [1., 0., 1.]])

In [4]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''

[[26.59948885 47.53904807 54.11469174]
 [70.68669942  6.86886691  4.57672874]]
[[27. 48. 54.]
 [71.  7.  5.]]
[[27. 48. 54.]
 [71.  7.  5.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [6]:
m = 20
n = 40

from numpy.random import default_rng
rng = default_rng()
rng.integers(m,n, size = (2,3))

array([[30, 29, 38],
       [25, 34, 30]])

In [4]:
# Answer
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

print(a)
print((a - b % 1) + m)

[[10.09870219 16.62441189  4.50574467]
 [14.24287556 15.03518226 11.31213177]]
[[30. 36. 24.]
 [34. 35. 31.]]


In [5]:
b%1


array([[0.09870219, 0.62441189, 0.50574467],
       [0.24287556, 0.03518226, 0.31213177]])