# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [5]:
import numpy as np

a = np.random.rand(2,3,2)
print(a)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
print(a.sum(axis=0))
print(a.sum(axis=1))

[[[0.91663116 0.75326552]
  [0.44494434 0.72275092]
  [0.82542142 0.9511446 ]]

 [[0.46128665 0.35189577]
  [0.44436422 0.55905445]
  [0.84239074 0.70835707]]]
7.9815068545328804
7.9815068545328804
[[1.3779178  1.10516128]
 [0.88930857 1.28180537]
 [1.66781217 1.65950166]]
[[1.3779178  1.10516128]
 [0.88930857 1.28180537]
 [1.66781217 1.65950166]]
[[2.18699692 2.42716103]
 [1.74804161 1.61930729]]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [15]:
A = np.random.random((5, 5))
A

array([[0.97538652, 0.94384254, 0.24207504, 0.26994681, 0.14349457],
       [0.91357125, 0.68938087, 0.90178847, 0.01362238, 0.68781373],
       [0.07153613, 0.54354524, 0.46699235, 0.48972854, 0.54281923],
       [0.52713675, 0.31971527, 0.81264265, 0.22137176, 0.80074472],
       [0.97469484, 0.31588679, 0.33330733, 0.74764018, 0.79479553]])

In [17]:
print(A.min())
print(A.max())

0.013622379177600674
0.9753865207000411


In [18]:
(A-A.min())/(A.max()-A.min())

array([[1.        , 0.96720196, 0.23753501, 0.26651486, 0.13503539],
       [0.9357272 , 0.70262392, 0.92347599, 0.        , 0.70099448],
       [0.06021617, 0.55099045, 0.47139413, 0.49503422, 0.55023558],
       [0.53392963, 0.3182619 , 0.83078609, 0.21600866, 0.81841515],
       [0.99928082, 0.31428123, 0.33239433, 0.76319938, 0.81222944]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [10]:
B = np.random.random(10)
B

array([0.75749483, 0.1979526 , 0.94744197, 0.35046278, 0.15623533,
       0.92709845, 0.17178115, 0.00952812, 0.67143877, 0.69311708])

In [13]:
B[B.argmax()] = -1
B

array([ 0.75749483,  0.1979526 , -1.        ,  0.35046278,  0.15623533,
        0.92709845,  0.17178115,  0.00952812,  0.67143877,  0.69311708])