# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


# 作業 

In [2]:
import numpy as np

In [4]:
a = np.arange(5)
b = np.arange(6).reshape(2,3)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
print('list(b): ', list(b))
print('tolist(): ', b.tolist())

list(a):  [0, 1, 2, 3, 4]
tolist():  [0, 1, 2, 3, 4]
list(b):  [array([0, 1, 2]), array([3, 4, 5])]
tolist():  [[0, 1, 2], [3, 4, 5]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [11]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[4 1 2 6 9 4]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [12]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[0 5 4 7]
 [6 8 4 4]
 [9 7 6 2]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [13]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 5]
  [2 5]
  [6 4]]

 [[8 3]
  [9 8]
  [1 2]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [14]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[8, 5, 1, 7, 5, 7]
[8, 5, 1, 7, 5, 7]


In [15]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 3, 5, 3], [3, 0, 6, 1], [2, 0, 7, 3]]
[array([1, 3, 5, 3]), array([3, 0, 6, 1]), array([2, 0, 7, 3])]


In [16]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[6, 7], [3, 9], [9, 6]], [[4, 2], [5, 3], [7, 1]]]
[array([[6, 7],
       [3, 9],
       [9, 6]]), array([[4, 2],
       [5, 3],
       [7, 1]])]


In [33]:
def tolist(iterable):
    if iterable.ndim ==1:
        return list(iterable)
    elif iterable.ndim ==2:
        return [list(i) for i in list(b)]
    else:
        return [list(list(j) for j in i) for i in list(c)]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 5, 1, 7, 5, 7]
[[1, 3, 5, 3], [3, 0, 6, 1], [2, 0, 7, 3]]
[[[6, 7], [3, 9], [9, 6]], [[4, 2], [5, 3], [7, 1]]]


In [36]:
## Answer
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(i) for i in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 5, 1, 7, 5, 7]
[[1, 3, 5, 3], [3, 0, 6, 1], [2, 0, 7, 3]]
[[[6, 7], [3, 9], [9, 6]], [[4, 2], [5, 3], [7, 1]]]


In [31]:
[list(list(j) for j in i) for i in list(c)]

[[[6, 7], [3, 9], [9, 6]], [[4, 2], [5, 3], [7, 1]]]