# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np 

print(np.searchsorted([1,2,4,3,5], 3))
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [1, 10, 3, 5]
))

2
[0 5 2 4]


In [3]:
a = np.random.rand(5)
print(a)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

[0.45994617 0.15680464 0.05022998 0.38936387 0.3708164 ]
1.4271610565187025
1.4271610565187025
1.4271610565187025


In [5]:
a = np.random.rand(3,4)
print(a)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

[[0.97854644 0.86793028 0.97099613 0.05792623]
 [0.5663261  0.99422727 0.68430209 0.54190019]
 [0.57283994 0.34929399 0.17333835 0.01767777]]
6.775304776313803
6.775304776313803
[2.11771247 2.21145154 1.82863656 0.6175042 ]


In [8]:
a = np.random.rand(2,3,2)
print(a)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
print(a.sum(axis=0))

[[[0.24030491 0.32358676]
  [0.05913469 0.60340224]
  [0.15601954 0.28744097]]

 [[0.1173127  0.31625533]
  [0.21915511 0.39944023]
  [0.37432048 0.81827444]]]
3.914647403417917
3.914647403417917
[[0.35761761 0.6398421 ]
 [0.2782898  1.00284246]
 [0.53034003 1.10571541]]
[[0.35761761 0.6398421 ]
 [0.2782898  1.00284246]
 [0.53034003 1.10571541]]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [15]:
A = np.random.random((5, 5))
A

array([[0.97538652, 0.94384254, 0.24207504, 0.26994681, 0.14349457],
       [0.91357125, 0.68938087, 0.90178847, 0.01362238, 0.68781373],
       [0.07153613, 0.54354524, 0.46699235, 0.48972854, 0.54281923],
       [0.52713675, 0.31971527, 0.81264265, 0.22137176, 0.80074472],
       [0.97469484, 0.31588679, 0.33330733, 0.74764018, 0.79479553]])

In [17]:
print(A.min())
print(A.max())

0.013622379177600674
0.9753865207000411


In [18]:
(A-A.min())/(A.max()-A.min())

array([[1.        , 0.96720196, 0.23753501, 0.26651486, 0.13503539],
       [0.9357272 , 0.70262392, 0.92347599, 0.        , 0.70099448],
       [0.06021617, 0.55099045, 0.47139413, 0.49503422, 0.55023558],
       [0.53392963, 0.3182619 , 0.83078609, 0.21600866, 0.81841515],
       [0.99928082, 0.31428123, 0.33239433, 0.76319938, 0.81222944]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [10]:
B = np.random.random(10)
B

array([0.75749483, 0.1979526 , 0.94744197, 0.35046278, 0.15623533,
       0.92709845, 0.17178115, 0.00952812, 0.67143877, 0.69311708])

In [13]:
B[B.argmax()] = -1
B

array([ 0.75749483,  0.1979526 , -1.        ,  0.35046278,  0.15623533,
        0.92709845,  0.17178115,  0.00952812,  0.67143877,  0.69311708])